### PR TITLE
Assignment 1 done

### PR DESCRIPTION
**Pull request by ritika1408**

### CODE REVIEW

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
Remove all .exe and .o file. You can do it in a second using git bash. Go these steps;
```
cd DSA-Bootcamps
rm *.exe
rm *.o
```

**Comment by ritika1408** [comment]
> Everything is perfect, just need small changes, Remove all .exe and .o files. You can do it in a second using git bash. Go through these steps;
> 
> ```
> cd DSA-Bootcamps
> rm *.exe
> rm *.o
> ```

@Vishal-raj-1  Done

**Review by Vishal-raj-1 — APPROVED** [review]
Awesome !!

**Comment by Vishal-raj-1** [comment]
In the next assignment make sure to delete the ritika.txt.txt file it was for demo purpose only.

**Pull request merged**
